import { Injectable, inject } from '@angular/core';
import { SupabaseService } from '../../../core/services/supabase.service';
import { TravelStore } from '../../../core/store/travel.store';
import { PhotoCapture } from '../../../core/services/camera.service';
import { Trip } from '../../../core/models/trip.model';
import { Expense } from '../../../core/models/expense.model';
import { Post } from '../../../core/models/social.model';
import { compressImage } from '../../../core/utils/image.util';

export interface SubmitMomentPayload {
  tripId: string;
  trip: Trip | null;
  photos: PhotoCapture[];
  caption: string;
  pendingNewMembers: any[];
  isExpenseMode: boolean;
  expenseAmount: number;
  paidById: string;
  selectedCategory: string;
  selectedLocation: any | null;
  pendingReceipts: {url: string, file?: File}[];
  splits: Record<string, number>;
}

export interface SubmitMomentResult {
  success: boolean;
  isAutoGeneratedTrip: boolean;
  finalTripId: string;
}

@Injectable({
  providedIn: 'root'
})
export class AddMomentService {
  private supabase = inject(SupabaseService);
  private travelStore = inject(TravelStore);

  async submitMoment(payload: SubmitMomentPayload): Promise<SubmitMomentResult> {
    const db = this.supabase.client;
    const uid = this.travelStore.currentUserId();
    
    let tripId = payload.tripId;
    let trip = payload.trip;
    let isAutoGeneratedTrip = false;
    let paidById = payload.paidById;
    let splits = { ...payload.splits };

    // Tracking uploaded files to clean up (rollback) if an error occurs later
    const uploadedMediaPaths: string[] = [];

    try {
      // 1. Auto-generate trip if needed
      if (tripId === 'NEW_TRIP') {
        const todayStr = new Date().toLocaleDateString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' });
        const defaultName = `Chuyến đi ngày ${todayStr}`;
        const todaySqlStr = new Date().toISOString().split('T')[0];
        
        const newTripPayload = {
          title: defaultName,
          start_date: todaySqlStr,
          end_date: todaySqlStr,
          cover_image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=2021&auto=format&fit=crop',
          owner_id: uid,
          is_private: true,
          members: [{
            id: uid,
            name: this.travelStore.currentUserProfile()?.name || 'You',
            email: '', 
            isMe: true,
            avatar: this.travelStore.currentUserProfile()?.avatar
          }]
        };

        const { data: createdTripData, error: createErr } = await db.from('trips').insert(newTripPayload).select().single();
        if (createErr || !createdTripData) throw new Error('Không thể tạo chuyến đi tự động.');
        
        tripId = createdTripData.id;
        trip = {
           id: tripId,
           title: defaultName,
           startDate: todaySqlStr,
           endDate: todaySqlStr,
           coverImage: newTripPayload.cover_image,
           ownerId: uid,
           isPrivate: true,
           members: newTripPayload.members as any
        } as Trip;
        isAutoGeneratedTrip = true;
      }

      if (!trip) throw new Error('Không tìm thấy dữ liệu chuyến đi');

      // 2. Process Pending Members
      if (payload.pendingNewMembers.length > 0) {
        const resolvedMembers: any[] = [];
        const idMap: Record<string, string> = {};
        
        for (const p of payload.pendingNewMembers) {
          let userId: string | null = null;
          let userName = p.name;
          let userAvatar: string | undefined = p.avatar;
          
          try {
            if (p.email) {
              const { data, error } = await db.functions.invoke('invite-member', { body: { email: p.email } });
              if (!error && data?.userId) {
                userId = data.userId;
                try {
                  const { data: userData } = await db.from('users').select('full_name, avatar_url').eq('id', userId).maybeSingle();
                  if (userData?.['full_name']) userName = userData['full_name'];
                  if (userData?.['avatar_url']) userAvatar = userData['avatar_url'];
                } catch(e) {}
              }
            }
          } catch(err) { console.warn('Invite fail', p.email, err); }
          
          if (!userId) userId = crypto.randomUUID();
          
          idMap[p.id] = userId;
          resolvedMembers.push({ ...p, id: userId, name: userName, avatar: userAvatar });
        }
        
        // Update Trip in DB
        const updatedTripMembers = [...trip.members, ...resolvedMembers];
        const { error: updateTripErr } = await db.from('trips').update({ members: updatedTripMembers }).eq('id', trip.id);
        if (updateTripErr) throw new Error('Lỗi khi cập nhật thành viên chuyến đi.');
        
        this.travelStore.updateTrip(trip.id, { members: updatedTripMembers });

        // Update IDs in splits and paidById
        if (idMap[paidById]) {
          paidById = idMap[paidById];
        }
        const newSplits: Record<string, number> = {};
        Object.keys(splits).forEach(k => {
          const mappedId = idMap[k] || k;
          newSplits[mappedId] = splits[k];
        });
        splits = newSplits;
      }

      // 3. Upload Photos (Parallel Upload)
      const isAnyDual = payload.photos.some(p => p.isDual);
      const photoPromises = payload.photos.map(async (p) => {
        const compressedFile = await compressImage(p.file, 1920, 1920, 0.8);
        const path = `posts/${uid}/${p.id}_${compressedFile.name}`;
        uploadedMediaPaths.push(path); // Save path for potential rollback
        const { data, error } = await db.storage.from('nomadsync-media').upload(path, compressedFile, { upsert: true });
        if (error || !data) throw new Error(`Lỗi khi tải ảnh ${compressedFile.name} lên máy chủ.`);
        
        const { data: urlData } = db.storage.from('nomadsync-media').getPublicUrl(path);
        return urlData.publicUrl;
      });
      const uploadedUrls = await Promise.all(photoPromises);

      // 4. Create Expense (Parallel Upload for Receipts)
      if (payload.isExpenseMode && payload.expenseAmount > 0) {
        const receiptPromises = payload.pendingReceipts.map(async (rec) => {
          if (rec.file) {
            const compressedFile = await compressImage(rec.file, 1920, 1920, 0.8);
            const rPath = `receipts/${uid}/${Date.now()}_${compressedFile.name.replace(/[^a-zA-Z0-9.\-]/g,'_')}`;
            uploadedMediaPaths.push(rPath); // Save path for potential rollback
            const { data: rData, error } = await db.storage.from('nomadsync-media').upload(rPath, compressedFile, { upsert: true });
            if (error || !rData) throw new Error(`Lỗi khi tải hóa đơn ${compressedFile.name} lên máy chủ.`);
            
            const { data: rUrlData } = db.storage.from('nomadsync-media').getPublicUrl(rPath);
            return rUrlData.publicUrl;
          }
          return rec.url;
        });
        const finalReceiptUrls = await Promise.all(receiptPromises);

        const expensePayload = {
          trip_id: tripId, 
          description: payload.caption || (payload.selectedCategory ? payload.selectedCategory.charAt(0).toUpperCase() + payload.selectedCategory.slice(1).toLowerCase() : 'Expense'), 
          amount: payload.expenseAmount,
          category: payload.selectedCategory, 
          payer_id: paidById,
          splits: splits, 
          receipt_urls: finalReceiptUrls
        };
        const { data, error: expenseErr } = await db.from('expenses').insert(expensePayload).select().single();
        if (expenseErr || !data) throw new Error('Lỗi khi tạo chi phí.');
        
        this.travelStore.upsertExpense({
          id: data['id'], tripId: data['trip_id'], desc: data['description'], amount: data['amount'],
          category: data['category'], payerId: data['payer_id'], date: data['date'], splits: data['splits']
        } as Expense);
      }
      
      // 5. Create Post
      const member = trip?.members.find((m: any) => m.id === uid);
      const authorName = this.travelStore.currentUserProfile()?.name || member?.name || 'Traveler';

      const postPayload = {
        trip_id: tripId, user_id: uid, content: payload.caption, image_urls: uploadedUrls,
        is_dual_camera: isAnyDual, location_name: payload.selectedLocation?.name ?? null,
        location_city: payload.selectedLocation?.city ?? null, likes: [], comment_count: 0
      };
      const { data: postData, error: postErr } = await db.from('posts').insert(postPayload).select().single();
      if (postErr || !postData) throw new Error('Lỗi khi đăng bài viết.');
      
      this.travelStore.addPost({
        id: postData['id'], tripId: postData['trip_id'], authorId: uid, authorName,
        content: postData['content'], images: postData['image_urls'] ?? [], isDual: postData['is_dual_camera'],
        timestamp: postData['created_at'], date: postData['created_at']?.split('T')[0],
        likes: 0, hasLiked: false, commentCount: 0
      } as Post);

      return {
        success: true,
        isAutoGeneratedTrip,
        finalTripId: tripId
      };

    } catch (error: any) {
      console.error('[AddMomentService] Lỗi khi tạo moment:', error);
      
      // ROLLBACK: Xóa các file ảnh/hóa đơn đã upload nếu tiến trình bị lỗi giữa chừng
      if (uploadedMediaPaths.length > 0) {
        console.warn('[AddMomentService] Đang rollback (xóa) các file đã upload...', uploadedMediaPaths);
        await db.storage.from('nomadsync-media').remove(uploadedMediaPaths).catch(e => {
           console.error('[AddMomentService] Rollback file thất bại:', e);
        });
      }
      
      // Ném lỗi ra cho UI xử lý (hiển thị Toast/Alert)
      throw new Error(error.message || 'Có lỗi xảy ra trong quá trình đăng bài. Vui lòng thử lại.');
    }
  }
}
