import { Injectable, inject } from '@angular/core';
import { SupabaseService } from '../../../core/services/supabase.service';
import { TravelStore } from '../../../core/store/travel.store';
import { PhotoCapture } from '../../../core/services/camera.service';
import { Trip } from '../../../core/models/trip.model';
import { Expense } from '../../../core/models/expense.model';
import { Post } from '../../../core/models/social.model';

export interface SubmitMomentPayload {
  tripId: string;
  trip: Trip | null;
  photos: PhotoCapture[];
  caption: string;
  pendingNewMembers: any[];
  isExpenseMode: boolean;
  expenseAmount: number;
  paidById: string;
  selectedCategory: string;
  selectedLocation: any | null;
  pendingReceipts: {url: string, file?: File}[];
  splits: Record<string, number>;
}

export interface SubmitMomentResult {
  success: boolean;
  isAutoGeneratedTrip: boolean;
  finalTripId: string;
}

@Injectable({
  providedIn: 'root'
})
export class AddMomentService {
  private supabase = inject(SupabaseService);
  private travelStore = inject(TravelStore);

  async submitMoment(payload: SubmitMomentPayload): Promise<SubmitMomentResult> {
    const db = this.supabase.client;
    const uid = this.travelStore.currentUserId();
    
    let tripId = payload.tripId;
    let trip = payload.trip;
    let isAutoGeneratedTrip = false;
    let paidById = payload.paidById;
    let splits = { ...payload.splits };

    // 1. Auto-generate trip if needed
    if (tripId === 'NEW_TRIP') {
      const todayStr = new Date().toLocaleDateString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' });
      const defaultName = `Chuyến đi ngày ${todayStr}`;
      const todaySqlStr = new Date().toISOString().split('T')[0];
      
      const newTripPayload = {
        title: defaultName,
        start_date: todaySqlStr,
        end_date: todaySqlStr,
        cover_image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=2021&auto=format&fit=crop',
        owner_id: uid,
        is_private: true,
        members: [{
          id: uid,
          name: this.travelStore.currentUserProfile()?.name || 'You',
          email: '', 
          isMe: true,
          avatar: this.travelStore.currentUserProfile()?.avatar
        }]
      };

      const { data: createdTripData, error: createErr } = await db.from('trips').insert(newTripPayload).select().single();
      if (createErr || !createdTripData) throw new Error('Không thể tạo chuyến đi tự động.');
      
      tripId = createdTripData.id;
      trip = {
         id: tripId,
         title: defaultName,
         startDate: todaySqlStr,
         endDate: todaySqlStr,
         coverImage: newTripPayload.cover_image,
         ownerId: uid,
         isPrivate: true,
         members: newTripPayload.members as any
      } as Trip;
      isAutoGeneratedTrip = true;
    }

    if (!trip) throw new Error('Không tìm thấy dữ liệu chuyến đi');

    // 2. Process Pending Members
    if (payload.pendingNewMembers.length > 0) {
      const resolvedMembers: any[] = [];
      const idMap: Record<string, string> = {};
      
      for (const p of payload.pendingNewMembers) {
        let userId: string | null = null;
        let userName = p.name;
        let userAvatar: string | undefined = p.avatar;
        
        try {
          const { data, error } = await db.functions.invoke('invite-member', { body: { email: p.email } });
          if (!error && data?.userId) {
            userId = data.userId;
            try {
              const { data: userData } = await db.from('users').select('full_name, avatar_url').eq('id', userId).maybeSingle();
              if (userData?.['full_name']) userName = userData['full_name'];
              if (userData?.['avatar_url']) userAvatar = userData['avatar_url'];
            } catch(e) {}
          }
        } catch(err) { console.warn('Invite fail', p.email, err); }
        
        if (!userId) userId = crypto.randomUUID();
        
        idMap[p.id] = userId;
        resolvedMembers.push({ ...p, id: userId, name: userName, avatar: userAvatar });
      }
      
      // Update Trip in DB
      const updatedTripMembers = [...trip.members, ...resolvedMembers];
      await db.from('trips').update({ members: updatedTripMembers }).eq('id', trip.id);
      this.travelStore.updateTrip(trip.id, { members: updatedTripMembers });

      // Update IDs in splits and paidById
      if (idMap[paidById]) {
        paidById = idMap[paidById];
      }
      const newSplits: Record<string, number> = {};
      Object.keys(splits).forEach(k => {
        const mappedId = idMap[k] || k;
        newSplits[mappedId] = splits[k];
      });
      splits = newSplits;
    }

    // 3. Upload Photos
    const uploadedUrls: string[] = [];
    let isAnyDual = false;
    for (const p of payload.photos) {
      const path = `posts/${uid}/${p.id}_${p.file.name}`;
      const { data } = await db.storage.from('nomadsync-media').upload(path, p.file, { upsert: true });
      if (data) {
        const { data: urlData } = db.storage.from('nomadsync-media').getPublicUrl(path);
        uploadedUrls.push(urlData.publicUrl);
        if (p.isDual) isAnyDual = true;
      }
    }

    // 4. Create Expense
    if (payload.isExpenseMode && payload.expenseAmount > 0) {
      let finalReceiptUrls: string[] = [];
      for (const rec of payload.pendingReceipts) {
         if (rec.file) {
            const rPath = `receipts/${uid}/${Date.now()}_${rec.file.name.replace(/[^a-zA-Z0-9.\-]/g,'_')}`;
            const { data: rData } = await db.storage.from('nomadsync-media').upload(rPath, rec.file, { upsert: true });
            if (rData) {
               const { data: rUrlData } = db.storage.from('nomadsync-media').getPublicUrl(rPath);
               finalReceiptUrls.push(rUrlData.publicUrl);
            }
         } else {
            finalReceiptUrls.push(rec.url);
         }
      }

      const expensePayload = {
        trip_id: tripId, 
        description: payload.caption || 'Untitled Expense', 
        amount: payload.expenseAmount,
        category: payload.selectedCategory, 
        payer_id: paidById,
        splits: splits, 
        receipt_urls: finalReceiptUrls
      };
      const { data } = await db.from('expenses').insert(expensePayload).select().single();
      if (data) {
        this.travelStore.upsertExpense({
          id: data['id'], tripId: data['trip_id'], desc: data['description'], amount: data['amount'],
          category: data['category'], payerId: data['payer_id'], date: data['date'], splits: data['splits']
        } as Expense);
      }
    }
    
    // 5. Create Post
    const member = trip?.members.find((m: any) => m.id === uid);
    const authorName = this.travelStore.currentUserProfile()?.name || member?.name || 'Traveler';

    const postPayload = {
      trip_id: tripId, user_id: uid, content: payload.caption, image_urls: uploadedUrls,
      is_dual_camera: isAnyDual, location_name: payload.selectedLocation?.name ?? null,
      location_city: payload.selectedLocation?.city ?? null, likes: [], comments: []
    };
    const { data: postData } = await db.from('posts').insert(postPayload).select().single();
    if (postData) {
      this.travelStore.addPost({
        id: postData['id'], tripId: postData['trip_id'], authorId: uid, authorName,
        content: postData['content'], images: postData['image_urls'] ?? [], isDual: postData['is_dual_camera'],
        timestamp: postData['created_at'], date: postData['created_at']?.split('T')[0],
        likes: 0, hasLiked: false, comments: []
      } as Post);
    }

    return {
      success: true,
      isAutoGeneratedTrip,
      finalTripId: tripId
    };
  }
}
